spring:
  web:
    # 静态资源处理
    resources:
      # 启用默认静态资源处理
      add-mappings: true
      cache:
        cache control:
          # 缓存响应时间，单位秒
          max-age: 3600
      chain:
        # 资源链启动缓存，默认启动
        cache: true
        #启动资源链，默认禁用
        enabled: true
        #压缩资源(gzip,brotli)解析，默认禁用
        compressed: true
      # 静态资源目录配置
      static-locations: classpath:/static/
  # thymeleaf配置
  thymeleaf:
    # 关闭缓存
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?userUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      # 连接池名字
      pool-name: DataHikariCP
      # 最小连接数
      minimum-idle: 5
      # 空闲连接最大存活时间，默认十分钟（600000），设置30min
      idle-timeout: 1800000
      # 最大连接数
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 最大存活时间。0表示永久存活，默认1800000（30min）
      max-lifetime: 1800000
      # 连接超时时间，默认30s
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  # redis配置
  data:
    redis:
      host: 192.168.7.0
      port: 6379
      # 默认数据库
      database: 0
      # 超时时间
      timeout: 10000ms
      lettuce:
        pool:
          # 最大连接数，默认为8
          max-active: 8
          # 最大连接或阻塞时间默认为-1
          max-wait:  10000ms
          # 最大空闲连接，默认8
          max-idle: 200
          # 默认0
          min-idle: 5
  # rabbitmq配置
  rabbitmq:
    # 主机ip
    host: 192.168.7.0
    # 用户
    username: guest
    # 密码
    password: guest
    # 虚拟主机
    virtual-host: /
    # 端口
    port: 5672
    listener:
      simple:
        # 消费者最小数量
        concurrency: 10
        # 消费者最大数量
        max-concurrency: 10
        # 限制消费者每次只处理一条消息
        prefetch: 1
        # 启动时是否默认启动容器，默认true
        auto-startup: true
        # 当消息被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        # 发布重试
        enabled: true
        # 重试时间默认1000ms
        initial-interval: 1000ms
        # 重试最大次数
        max-attempts: 3
        #重试最大间隔时间
        max-interval: 10000ms
        #重试间隔乘数，比如2.0，第一次10s,第二次20s，第三次40s
        multiplier: 1
# mybatis-plus配置
mybatis-plus:
  # 配置Mapper.xml映射位置
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置mybatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.cytus.seckilldemo.pojo

# Mybatis SQL 打印（方法接口所在的包），不是Mapper.xml
logging:
  level:
    com.cytus.seckilldemo.mapper: debug





